Repository RedHatInsights/sources-api, pull requests merged in 2019-11, with the labels that each got.

#118 adding patch for applications
  config/routes.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#124 Use initializeOnMount for hidden fields
  db/seeds/source_types.rb
Labels: bug

#126 [STABLE] Sprint 29
  Gemfile
  README.md
  app/controllers/api/v1/graphql_controller.rb
  app/controllers/api/v1/mixins/index_mixin.rb
  app/controllers/api/v1x0.rb
  app/controllers/application_controller.rb
  config/application.rb
  config/initializers/application_record_serializing.rb
  config/routes.rb
  db/seeds/source_types.rb
  lib/tasks/client_generate.rake
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
  spec/support/json_schema_matcher.rb
  spec/swagger_spec.rb
Labels: stable
