Repository RedHatInsights/sources-api, pull requests merged in 2019-12, with the labels that each got.

#128 Adding the POST /api/sources/:source_id/check_availability action
  app/controllers/api/v1/sources_controller.rb
  config/routes.rb
  lib/sources/api/events.rb
  lib/sources/api/messaging.rb
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/controllers/api/v1x0/endpoints_controller_spec.rb
  spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
  spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: enhancement

#134 Adding support for application availability checks
  Gemfile
  app/controllers/api/v1/sources_controller.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: enhancement

#141 [WIP] Updated sources-api to leverage environment for availability_check_urls
  app/controllers/api/v1/sources_controller.rb
  db/migrate/20191213165335_remove_availability_check_url_from_application_types.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/v1.0/sources_spec.rb
Labels: enhancement, wip

#142 Fix yml for Amazon ARN authentication
  db/seeds/source_types.yml
Labels: bug

#144 Exposing the sort_by parameter for queries.
  app/controllers/api/v1/mixins/index_mixin.rb
  app/controllers/application_controller.rb
  spec/requests/api/v1.0/filter_spec.rb
Labels: bug
