Repository RedHatInsights/sources-api, pull requests merged in 2019-08, with the labels that each got.

#63 Add back tenant to openapi schema
  lib/tasks/openapi_generate.rake
Labels: bug

#67 Add an API to list application_types per source
  config/routes.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#68 Add a dependent_applications to application_types
  db/migrate/20190823150955_add_dependent_applications_to_application_types.rb
  db/seeds.rb
Labels: enhancement

#69 Add supported_source_types and _authentication_types to application_type
  db/migrate/20190823151426_add_supported_source_types_to_application_types.rb
  db/migrate/20190823201412_add_supported_authentication_types.rb
  db/seeds.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#71 Use extracted request methods in ManageIQ::API::Common
  app/controllers/application_controller.rb
Labels: bug

#72 Sprint 23 stable branch
  app/controllers/application_controller.rb
  app/controllers/internal/v1/tenants_controller.rb
  app/models/application_type.rb
  app/models/source.rb
  config/routes.rb
  db/migrate/20190725224531_add_source_availability_status.rb
  db/migrate/20190809154221_add_extra_jsonb_to_authentications.rb
  db/migrate/20190823150955_add_dependent_applications_to_application_types.rb
  db/migrate/20190823151426_add_supported_source_types_to_application_types.rb
  db/migrate/20190823201412_add_supported_authentication_types.rb
  db/seeds.rb
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/v1.0/application_types_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: stable

#65 Add SourceTypeIcons Model and API
  db/migrate/20190829141221_add_icon_url_to_source_types.rb
  db/seeds.rb
  public/aws_logo.png
  public/doc/openapi-3-v1.0.0.json
  public/openshift_logo.png
  public/vsphere_logo.png
Labels: enhancement
