Repository RedHatInsights/sources-api, pull requests merged in 2019-06, with the labels that each got.

#32 Adding support for GraphQL
  app/controllers/api/graphql_controller.rb
  config/routes.rb
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_controller.rb
Labels: enhancement

#39 Add missing raise_event for Applications create
  app/controllers/api/v1/applications_controller.rb
Labels: enhancement

#43 Validate source name is uniqueness within tenant
  app/models/source.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: bug

#20 Entitlement enforcement
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
  spec/support/tenant_identity.rb
Labels: enhancement

#42 Updated the openapi generator to use the new graphql description
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
Labels: wip

#35 Updated the GraphQL specs to reflect the simplified query signature.
  spec/requests/api/graphql_controller.rb
Labels: wip
