Repository RedHatInsights/sources-api, pull requests merged in 2019-10, with the labels that each got.

#96 Return `tenant` in applications response
  lib/tasks/openapi_generate.rake
Labels: bug

#98 Update manageiq-api-common dependency
  Gemfile
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#104 Lockdown sprockets to ~>3.0 to fix failure on 2.4
  Gemfile
Labels: bug

#103 Fix Azure authentication_type
  db/seeds/application_types.rb
  db/seeds/source_types.rb
Labels: bug

#95 Add 404 return to OpenAPI spec for collections
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#99 Add tests with null values
  spec/requests/api/v1.0/sources_spec.rb
Labels: enhancement

#113 Update for ManageIQ::API::Common v2.0
  spec/requests/api/v1.0/sources_spec.rb
Labels: bug

#114 [STABLE] Sprint 27
  .travis.yml
  Gemfile
  app/controllers/application_controller.rb
  db/migrate/20191011124345_add_imported_to_sources.rb
  db/seeds/application_types.rb
  db/seeds/source_types.rb
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/filter_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: stable

#112 Add test for Authentication patch with extra attributes
  spec/requests/api/v1.0/authentications_spec.rb
Labels: bug

#116 Add AvailabilityStatus to Applications, Authentications, and Endpoints
  app/models/application.rb
  app/models/authentication.rb
  app/models/endpoint.rb
  db/migrate/20191028194041_add_availablility_status.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement
