Repository RedHatInsights/sources-api, pull requests merged in 2019-07, with the labels that each got.

#53 Add source types from cloudforms
  db/seeds.rb
Labels: enhancement

#52 Do not include `tenant` in any API responses
  app/models/concerns/tenancy_concern.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_controller_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
Labels: bug

#54 Stable branch for sprint 20
  .codeclimate.yml
  app/models/concerns/tenancy_concern.rb
  db/seeds.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_controller_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
Labels: stable

#56 Reinstating tenant in API responses
  app/models/concerns/tenancy_concern.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/api/graphql_controller_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
Labels: bug

#57 Normalize user name fields in json schema
  db/seeds.rb
Labels: bug

#61 Fix to the openapi spec to update the CollectionMetadata to include offset and limit
  lib/tasks/openapi_generate.rake
  public/doc/openapi-3-v1.0.0.json
Labels: bug
