Repository RedHatInsights/sources-api, pull requests merged in 2019-09, with the labels that each got.

#79 updating cost management database seeds.
  db/seeds/application_types.rb
Labels: enhancement

#81 Don't run db:migrate and db:seed together
  docker-assets/run_rails_server
Labels: bug

#82 Don't run db:migrate and db:seed together
  docker-assets/run_rails_server
Labels: bug, stable

#83 Add a endpoints.receptor_node attribute
  db/migrate/20190919143736_add_receptor_node_id_to_endpoints.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#84 Don't use real models when doing a data migration
  db/migrate/20190522195925_set_authentication_auth_type.rb
Labels: bug

#86 Fix typo in application_types.db
  db/seeds/application_types.rb
Labels: bug

#91 Add return type to getDocumentation /openapi.json
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#92 Use the released manageiq-api-common gem
  Gemfile
Labels: enhancement
