Repository RedHatInsights/sources-api, pull requests merged in 2020-01, with the labels that each got.

#147 Drop to a single puma thread and log before and after publishing to kafka
  app/controllers/api/v1/sources_controller.rb
  app/controllers/application_controller.rb
  config/puma.rb
Labels: bug

#149 Upgrading puma gem to 3.12.2 to fix Hakiri warning
  Gemfile
Labels: bug

#154 Set manageiq-loggers to a minimum of 0.4.2
  Gemfile
Labels: bug

#156 Cache kafka connection per thread
  config/puma.rb
  lib/sources/api/events.rb
  lib/sources/api/messaging.rb
  spec/controllers/api/v1x0/endpoints_controller_spec.rb
  spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
  spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: enhancement

#159 Don't share a kafka connection
  lib/sources/api/events.rb
  lib/sources/api/messaging.rb
  spec/controllers/api/v1x0/endpoints_controller_spec.rb
  spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
  spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
  spec/requests/api/v1.0/authentications_spec.rb
  spec/requests/api/v1.0/source_types_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
Labels: bug

#145 Only allow org-admin to be able to use the sources-api.
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
  spec/requests/api/v1.0/sources_spec.rb
  spec/support/tenant_identity.rb
Labels: enhancement

#167 Fix the application controller events spec
  spec/controllers/application_controller_spec.rb
Labels: bug

#157 [WIP] StatusController for Liveness Probe
  app/controllers/status_controller.rb
  config/routes.rb
  spec/swagger_spec.rb
Labels: wip

#151 Added a timeout to the application availability checks performed.
  app/controllers/api/v1/sources_controller.rb
Labels: enhancement
